config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :clients
  resources :activities
  resources :records

  root to: 'records#index'

  get '/home' => 'records#index'


end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :manager, required: false
  belongs_to :client, required: false
  belongs_to :activity_type, required: false
  belongs_to :provider, required: false
  belongs_to :record, inverse_of: :activities
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  has_many :activities
end

app/models/age_range_type.rb
class AgeRangeType < ApplicationRecord
  has_many :clients
end

app/models/change_type.rb
class ChangeType < ApplicationRecord
  has_many :clients
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :activities
  belongs_to :age_range_type, required: false
  belongs_to :exit_attempt_type, required: false
  belongs_to :family_type, required: false
  belongs_to :relationship_type, required: false
  belongs_to :gender_type, required: false
  belongs_to :risk_level_type, required: false
  belongs_to :participation_type, required: false
  belongs_to :change_type, required: false

  has_many :client_target_groups
  has_many :target_groups, through: :client_target_groups
  accepts_nested_attributes_for :client_target_groups

  has_many :client_referrals
  has_many :referrals, through: :client_referrals
  accepts_nested_attributes_for :client_referrals

  has_many :client_support_networks
  has_many :support_networks, through: :client_support_networks
  accepts_nested_attributes_for :client_support_networks

  has_many :client_substances
  has_many :substances, through: :client_substances
  accepts_nested_attributes_for :client_substances

  has_many :client_outcomes
  has_many :outcomes, through: :client_outcomes
  accepts_nested_attributes_for :client_outcomes

  validates :first_name, presence: true
  validates :initials, presence: true
end

app/models/client_outcome.rb
class ClientOutcome < ApplicationRecord
  belongs_to :client
  belongs_to :outcome
end

app/models/client_referral.rb
class ClientReferral < ApplicationRecord
  belongs_to :client
  belongs_to :referral
end

app/models/family_type.rb
class FamilyType < ApplicationRecord
  has_many :clients
end

app/models/gender_type.rb
class GenderType < ApplicationRecord
  has_many :clients
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :activities
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  has_many :outcomes
  has_many :clients, through: :outcomes
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :activities
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :manager
  belongs_to :client
  belongs_to :stage
  belongs_to :risk_level_start
  belongs_to :risk_level_end
  has_many :activities, inverse_of: :record
  accepts_nested_attributes_for :activities, :allow_destroy => true
  after_commit :update_activity_attributes

  private

  def update_activity_attributes
    activities = self.activities
    activities.each do |activity|
      activity.update_attributes(client_id:self.client_id, manager_id:self.manager_id)
    end
  end

  def self.recent_records
    records = self.where("start_date >= ?", (Date.current - 2))
    records
  end

  def self.older_records
    records = self.where("start_date < ?", (Date.current - 2))
    records
  end
end

app/models/referral.rb
class Referral < ApplicationRecord
  has_many :client_referrals
  has_many :clients, through: :client_referrals
end

app/models/risk_level_end.rb
class RiskLevelEnd < ApplicationRecord
  has_many :clients
  has_many :records
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :records
end

app/models/substance.rb
class Substance < ApplicationRecord
  has_many :client_substances
  has_many :clients, through: :client_substances
end

app/models/target_group.rb
class TargetGroup < ApplicationRecord
  has_many :client_target_groups
  has_many :clients, through: :client_target_groups
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  require 'time'
  require 'date'
  helper :records

  def index
    @recent_records = Record.recent_records
    @older_records  = Record.older_records
  end

  def new
    @record = Record.new
  end

  def edit
    @record = Record.find(params[:id])
  end

  def show
    @record = Record.find(params[:id])
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to records_path
    else
      render :new
    end
  end

  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(record_params)
      redirect_to @record, notice: 'Successfully updated record'
    else
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path
  end

  private
    def record_params
      params.require(:record).permit(:start_date, :end_date, :manager_id, :client_id, :notes, :steps_taken, :risk_level_start_id, :risk_level_end_id, :closed, :stage_id, :created_at, :updated_at, activities_attributes: [:id, :start_date, :end_date, :duration, :activity_type_id, :client_id, :manager_id, :provider_id, :created_at, :updated_at, :_destroy])
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
  def get_manager_id(current_user)
    if current_user != nil
      if current_user.email != nil
        manager = Manager.where(email:current_user.email)
        if manager.length == 1
          manager_id = manager.first.id
        elsif manager.length > 1
          puts "too many managers"
          manager_id == 1
        elsif manager.length < 1
          puts "no manager"
          manager_id == 1
        end
      end
    end
    manager_id
  end
end

app/views/records/_activity_fields.erb
<div class="nested-fields well well-compact inline-form">
  <div>
    <%= f.input :start_date, ampm: true, as: :datetime, order: [:day, :month, :year], required: true %>
    <%= f.input :activity_type_id, collection: ActivityType.all, required: true %>
    <%= f.input :duration, label: 'Duration (hrs)', :class =>'form-control', :input_html => {:style=> 'width: 150px' }, required: true  %>
    <%= f.association :provider, label: 'Partner', label_method: :name, value_method: :id%>
    <p>
    <%= link_to_remove_association f do %>
      <i class="glyphicon glyphicon-remove"></i>
    <%end%>
    </p>
   </div>
</div>

app/views/records/_record_form.html.erb
<div class="well">

    <%= simple_form_for(@record, html: { class: 'form-horizontal' }) do |f| %>

    <p>
      <%= f.hidden_field :manager_id, :value => get_manager_id(current_user)%>
    </p>
    <p>
      <%= f.association :client, label_method: :first_name, value_method: :id, required: true%>
    </p>
    <p>
      <%= f.association :risk_level_start,  required: true %>
    <p>
      <%= f.input :start_date, as: :date, order: [:day, :month, :year], required: true %>
    </p>
    <h3>Activities</h3>

    <div id="activities">
      <%= f.simple_fields_for :activities do |activity| %>
        <%= render 'activity_fields', :f => activity %>
      <%end%>
      <div class="btn btn-default">
        <%=link_to_add_association 'Add New Activity', f, :activities%>
      </div>
    </div>
    <p>
      <%= f.input :steps_taken, as: :text, :input_html => {:rows => 5}  %>
    </p>
    <p>
      <%= f.input :notes, as: :text, :input_html => {:rows => 5}  %>
    </p>
    <p>
      <%= f.association :risk_level_end, required: true %>
    <p>
    <p>
      <%= f.association :stage, required: true%>
    </p>
    <div>
      <%= f.button :submit%>
    </div>
  <% end %>
</div>

app/views/records/_record_view.html.erb
<div>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start Date</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
   </thead>
   <% records.each do |record| %>
    <tr>
      <td id="name">
        <%=Client.find(record.client_id).first_name%>
      </td>
      <td id="name">
        <%=record.start_date.strftime("%b %d, %y")%>
      </td>
      <td><%= button_to('View', record_path(record), method: :get, :class => 'btn btn-default btn-sm')%>
      </td>
      <td><%= button_to('Edit', edit_record_path(record), method: :get, :class => 'btn btn-default btn-sm')%>
      </td>
      <td><%= button_to 'Delete', record_path(record), :class => 'btn btn-default btn-sm',
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </td>
     <%end%>
  </table>
</div>

app/views/records/edit.html.erb
<div class="container-fluid">
   <div class="row col-xs-12 col-md-8 ">
      <h2> Edit case </h2>
         <%=render "record_form"%>
   </div>
</div>

app/views/records/index.html.erb
<div class="container-fluid ">
  <div>
    <div class="row col-xs-12">
      <div id= "links" class="actions">
        <%= button_to 'New Record', new_record_path, method: :get, :class => 'btn  btn-primary pull-right btn-padded'  %>
      </div>
    </div>
  </div>
   <div class="row col-xs-12 col-md-8 ">
   </div>
   <div class="row col-xs-12 col-md-8 ">
     <h3> Recent Records </h3>
      <%= render partial:'record_view', locals: {records: @recent_records} %>
     <h3> Records older than two days </h3>
      <%= render partial:'record_view', locals: {records: @older_records} %>
   </div>
</div>

app/views/records/new.html.erb
<div class="container-fluid">
   <div class="row col-xs-12 col-md-8 ">
      <h2> Add a new case record </h2>
         <%=render "record_form"%>
   </div>
</div>

app/views/records/show.html.erb
<div class="container-fluid">
  <div id= "links" class="row col-xs-6 actions">
    <%= button_to('Edit', edit_record_path(@record), method: :get, :class => 'btn  btn-primary pull-right btn-padded')%>
    <%= button_to('Back', records_path(@record), method: :get, :class => 'btn  btn-primary pull-right btn-padded')%>
  </div>
  <div class="row">
    <div class ="col-xs-1">
    </div>
      <div class="col-xs-8">
        <h2>Record Quick View </h2>
        <p>
          <span id="label"> Client Id: </span>
          <%if @record.client_id != nil%>
            <span id="name"><%=Client.find(@record.client_id).initials%></span>
          <%end%>
        </p>
        <p>
          <span id="label"> Manager: </span>
          <%if @record.manager_id != nil%>
            <span id="name"><%=Manager.find(@record.manager_id).first_name%></span>
          <%end%>
        </p>
        <p>
          <span id="label"> Start Date: </span>
          <span id="name"><%=@record.start_date.strftime("%b %d, %y")%></span>
        </p>
        <p>
          <span id="label"> Notes: </span>
          <span id="name"><%=@record.notes%></span>
        </p>
        <p>
          <span id="label"> Start Date: </span>
          <span id="name"><%=@record.steps_taken%></span>
        </p>
        <p>
          <span id="label"> Risk Level (Start): </span>
          <%if @record.risk_level_start_id != nil%>
            <span id="name"><%=RiskLevelStart.find(@record.risk_level_start_id).name%></span>
          <%end%>
        </p>
        <p>
          <span id="label"> Risk Level (End): </span>
          <%if @record.risk_level_end_id != nil%>
            <span id="name"><%=RiskLevelEnd.find(@record.risk_level_end_id).name%></span>
          <%end%>
        </p>
        <p>
          <span id="label"> Client Stage: </span>
          <%if @record.stage_id != nil%>
            <span id="name"><%=Stage.find(@record.stage_id).name%></span>
          <%end%>
        </p>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Activity # </th>
              <th>Activity Type</th>
              <th>Date and Time</th>
              <th>Partner</th>
              <th>Time (hrs) </th>
            </tr>
          </thead>
          <%activity_count = 0%>
          <%count = 0%>
          <%if @record.activities != nil%>
            <% @record.activities.each do |activity| %>
              <tr>
                <td id="name">
                  <%=activity_count +=1%>
                </td>
                <td id="name">
                  <%=ActivityType.find(activity.activity_type_id).name%>
                </td>
                <td id="name">
                  <%=activity.start_date.strftime("%b %d, %y, %l:%M %p ")%>
                </td>
                <td id="name">
                  <%if activity.provider_id != nil %>
                    <%=Provider.find(activity.provider_id).name%>
                    <%end%>
                </td>
                <td id="name">
                  <%=activity.duration%>
                  <%count += activity.duration%>
                </td>
              </tr>
            <%end%>
          <%end%>
            <tr>
              <th>Total</th>
              <td></td>
              <td></td>
              <th><%=count%></th>
            </tr>
        </table>
    </div>
  </div>
</div>