config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :clients
  resources :activities
  resources :records

  root to: 'records#index'

  get '/home' => 'records#index'


end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :manager, required: false
  belongs_to :client, required: false
  belongs_to :activity_type, required: false
  belongs_to :provider, required: false
  belongs_to :record, inverse_of: :activities
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  has_many :activities
end

app/models/age_range_type.rb
class AgeRangeType < ApplicationRecord
  has_many :clients
end

app/models/change_type.rb
class ChangeType < ApplicationRecord
  has_many :clients
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :activities
  belongs_to :age_range_type, required: false
  belongs_to :exit_attempt_type, required: false
  belongs_to :family_type, required: false
  belongs_to :relationship_type, required: false
  belongs_to :gender_type, required: false
  belongs_to :risk_level_type, required: false
  belongs_to :participation_type, required: false
  belongs_to :change_type, required: false

  has_many :client_target_groups
  has_many :target_groups, through: :client_target_groups
  accepts_nested_attributes_for :client_target_groups

  has_many :client_referrals
  has_many :referrals, through: :client_referrals
  accepts_nested_attributes_for :client_referrals

  has_many :client_support_networks
  has_many :support_networks, through: :client_support_networks
  accepts_nested_attributes_for :client_support_networks

  has_many :client_substances
  has_many :substances, through: :client_substances
  accepts_nested_attributes_for :client_substances

  has_many :client_outcomes
  has_many :outcomes, through: :client_outcomes
  accepts_nested_attributes_for :client_outcomes

  validates :first_name, presence: true
  validates :initials, presence: true
end

app/models/client_outcome.rb
class ClientOutcome < ApplicationRecord
  belongs_to :client
  belongs_to :outcome
end

app/models/client_referral.rb
class ClientReferral < ApplicationRecord
  belongs_to :client
  belongs_to :referral
end

app/models/family_type.rb
class FamilyType < ApplicationRecord
  has_many :clients
end

app/models/gender_type.rb
class GenderType < ApplicationRecord
  has_many :clients
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :activities
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  has_many :outcomes
  has_many :clients, through: :outcomes
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :activities
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :manager
  belongs_to :client
  belongs_to :stage
  belongs_to :risk_level_start
  belongs_to :risk_level_end
  has_many :activities, inverse_of: :record
  accepts_nested_attributes_for :activities, :allow_destroy => true
  after_commit :update_activity_attributes

  private

  def update_activity_attributes
    activities = self.activities
    activities.each do |activity|
      activity.update_attributes(client_id:self.client_id, manager_id:self.manager_id)
    end
  end

  def self.recent_records
    records = self.where("start_date >= ?", (Date.current - 2))
    records
  end

  def self.older_records
    records = self.where("start_date < ?", (Date.current - 2))
    records
  end
end

app/models/referral.rb
class Referral < ApplicationRecord
  has_many :client_referrals
  has_many :clients, through: :client_referrals
end

app/models/risk_level_end.rb
class RiskLevelEnd < ApplicationRecord
  has_many :clients
  has_many :records
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :records
end

app/models/substance.rb
class Substance < ApplicationRecord
  has_many :client_substances
  has_many :clients, through: :client_substances
end

app/models/target_group.rb
class TargetGroup < ApplicationRecord
  has_many :client_target_groups
  has_many :clients, through: :client_target_groups
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  require 'time'
  require 'date'

  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to activities_path
    else
      redirect_to activities_path
    end
  end

  def update
    @activity = Activity.where(id:params[:id]).first_or_initialize
    if @activity.update(activity_params)
      redirect_to activities_path
    else
      render 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end

  private
    def activity_params
      params.require(:activity).permit(:start_date, :end_date, :manager_id, :client_id, :duration, :activity_type_id, :created_at, :updated_at, :provider_id)
    end

    def activity_type_params
      params.require(:activity_type).permit(:name)
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
  def get_manager_id(current_user)
    if current_user != nil
      if current_user.email != nil
        manager = Manager.where(email:current_user.email)
        if manager.length == 1
          manager_id = manager.first.id
        elsif manager.length > 1
          puts "too many managers"
          manager_id == 1
        elsif manager.length < 1
          puts "no manager"
          manager_id == 1
        end
      end
    end
    manager_id
  end
end

app/views/activities/_activity_form.html.erb
<div class="well">

   <%= form_for @activity do |f|%>

    <p>
      <%= f.label "Case Manager"%><br>
      <%= f.collection_select(:manager_id, Manager.all, :id, :first_name, {:class =>'form-control'}) %>
   </p>
   <p>
      <%= f.label :client_id %><br>
      <%= f.collection_select(:client_id, Client.all, :id, :initials, {:class =>'form-control'}) %>
   </p>
    <p>
      <%= f.label "Service Provider" %><br>
      <%= f.collection_select(:provider_id, Provider.all, :id, :name, {:class =>'form-control'}) %>
   </p>
   <p>
      <%= f.label "Activity Type"%><br>
      <%= f.collection_select(:activity_type_id, ActivityType.all, :id, :name, {:class =>'form-control'}) %>
   </p>
   <p>
      <%= f.label :start_date %>
      <%= f.datetime_select :start_date %>
   </p>
    <p>
      <%= f.label :duration %><br>
      <%= f.text_field :duration %>
   </p>
   <div id= "buttonId" class="actions">
      <%= f.submit "Submit", class:"btn btn-primary btn-padded" %>
   </div>
   <% end %>
</div>

app/views/activities/edit.html.erb
<div class="container-fluid">
   <div class="row col-xs-8">
      <h2> Edit activity </h2>
         <%=render "activity_form"%>
   </div>
</div>

app/views/activities/index.html.erb
<div class="container-fluid ">
    <div>
      <div class="row col-xs-8">
        <div id= "links" class="actions">
          <%= button_to('New Client', new_client_path, :class => 'btn  btn-primary pull-right btn-padded')  %>
        </div>
      </div>
    </div>
   <div class="row col-xs-12 col-md-8 ">
      <div class="col-xs-6 previous">
         <h4>Clients</h4>
      </div>
   </div>
   <div class="row col-xs-12 col-md-8 ">
      <table id="student-table" class="table table-condensed">
         <thead>
            <tr>
               <th>Client Name</th>
               <th>Edit</th>
               <th>Delete</th>
            </tr>
         </thead>
         <% @clients.each do |client| %>
          <tr>
            <td id="name">
              <%=Client.find(client.client_id).first_name%>
           </td>
           <td><%= button_to('Edit', edit_client_path(client), :class => 'btn btn-default btn-sm')%>
           </td>
           <td><%= button_to 'Delete', client_path(client), :class => 'btn btn-default btn-sm',
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
               </td>
           <%end%>
      </table>
   </div>
</div>

app/views/activities/new.html.erb
<div class="container-fluid">
   <div class="row col-xs-8">
      <h2> Add a new Activity </h2>
         <%=render "activity_form"%>
   </div>
</div>