config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :clients
  resources :activities
  resources :records

  root to: 'records#index'

  get '/home' => 'records#index'


end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :manager, required: false
  belongs_to :client, required: false
  belongs_to :activity_type, required: false
  belongs_to :provider, required: false
  belongs_to :record, inverse_of: :activities
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  has_many :activities
end

app/models/age_range_type.rb
class AgeRangeType < ApplicationRecord
  has_many :clients
end

app/models/change_type.rb
class ChangeType < ApplicationRecord
  has_many :clients
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :activities
  belongs_to :age_range_type, required: false
  belongs_to :exit_attempt_type, required: false
  belongs_to :family_type, required: false
  belongs_to :relationship_type, required: false
  belongs_to :gender_type, required: false
  belongs_to :risk_level_type, required: false
  belongs_to :participation_type, required: false
  belongs_to :change_type, required: false

  has_many :client_target_groups
  has_many :target_groups, through: :client_target_groups
  accepts_nested_attributes_for :client_target_groups

  has_many :client_referrals
  has_many :referrals, through: :client_referrals
  accepts_nested_attributes_for :client_referrals

  has_many :client_support_networks
  has_many :support_networks, through: :client_support_networks
  accepts_nested_attributes_for :client_support_networks

  has_many :client_substances
  has_many :substances, through: :client_substances
  accepts_nested_attributes_for :client_substances

  has_many :client_outcomes
  has_many :outcomes, through: :client_outcomes
  accepts_nested_attributes_for :client_outcomes

  validates :first_name, presence: true
  validates :initials, presence: true
end

app/models/client_outcome.rb
class ClientOutcome < ApplicationRecord
  belongs_to :client
  belongs_to :outcome
end

app/models/family_type.rb
class FamilyType < ApplicationRecord
  has_many :clients
end

app/models/gender_type.rb
class GenderType < ApplicationRecord
  has_many :clients
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :activities
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  has_many :outcomes
  has_many :clients, through: :outcomes
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :activities
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :manager
  belongs_to :client
  belongs_to :stage
  belongs_to :risk_level_start
  belongs_to :risk_level_end
  has_many :activities, inverse_of: :record
  accepts_nested_attributes_for :activities, :allow_destroy => true
  after_commit :update_activity_attributes

  private

  def update_activity_attributes
    activities = self.activities
    activities.each do |activity|
      activity.update_attributes(client_id:self.client_id, manager_id:self.manager_id)
    end
  end

  def self.recent_records
    records = self.where("start_date >= ?", (Date.current - 2))
    records
  end

  def self.older_records
    records = self.where("start_date < ?", (Date.current - 2))
    records
  end
end

app/models/referral.rb
class Referral < ApplicationRecord
  has_many :client_referrals
  has_many :clients, through: :client_referrals
end

app/models/risk_level_end.rb
class RiskLevelEnd < ApplicationRecord
  has_many :clients
  has_many :records
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :records
end

app/models/substance.rb
class Substance < ApplicationRecord
  has_many :client_substances
  has_many :clients, through: :client_substances
end

app/models/target_group.rb
class TargetGroup < ApplicationRecord
  has_many :client_target_groups
  has_many :clients, through: :client_target_groups
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container">
      <ul class="nav nav-tabs">
        <% if user_signed_in? %>
          <li class="<%= 'active' if params[:controller] =='clients' %> nav-link nav-item"><%= link_to 'Clients', clients_path%></li>
          <li class="<%= 'active' if params[:controller] =='records' %> nav-link nav-item"><%= link_to 'Notes', records_path %></li>
          <li class="nav-link nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoiceFound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class="error_explanation">
  <h2><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>